version: '3.8'

services:
  pz_app_atendimento:
    image: kellyregis/pz_aten_disc:latest    
    restart: always
   # ports:
   #   - "3005:3005"
    volumes:
      # Arquivos de configuração
      - pz_app_atendimento_disc_data:/config.json:/app/config.json
      - pz_app_atendimento_disc_data:/dono.json:/app/dono.json
      - pz_app_atendimento_disc_data:/carrinhos.json:/app/carrinhos.json
      
      # Diretórios de dados
      - pz_app_atendimento_disc_data:/DataBaseJson:/app/DataBaseJson
      - pz_app_atendimento_disc_data:/ComandosSlash:/app/ComandosSlash
      - pz_app_atendimento_disc_data:/Eventos:/app/Eventos
      - pz_app_atendimento_disc_data:/Functions:/app/Functions
      - pz_app_atendimento_disc_data:/Handler:/app/Handler
      - pz_app_atendimento_disc_data:/Lib:/app/Lib
      - pz_app_atendimento_disc_data:/routes:/app/routes      
      # Arquivos de banco de dados
      - pz_app_atendimento_disc_data:/json.sqlite:/app/json.sqlite         
     
    environment:
      - NODE_ENV=production
    networks:
      - traefik_public
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.role == manager
        resources:
          limits:
            cpus: "0.5"
            memory: 512M  
    labels:
        - traefik.enable=true
        - traefik.http.routers.pz_app_atendimento.rule=Host(`tickets.servidorprojetoz.com.br`)        
        - traefik.http.routers.pz_app_atendimento.entrypoints=websecure
        - traefik.http.routers.pz_app_atendimento.tls.certresolver=letsencryptresolver
        - traefik.http.routers.pz_app_atendimento.service=pz_app_atendimento
        - traefik.http.services.pz_app_atendimento.loadbalancer.server.port=8087  

volumes:
  pz_app_atendimento_disc_data:
    external: true

networks:
  traefik_public:
    external: true